language: cpp
env:
- BUILD_VERSION=ffmpeg2
- BUILD_VERSION=ffmpeg3
- BUILD_VERSION=ffmpeg4
os: linux
dist: xenial
sudo: required

addons:
  apt:
    sources: &s_common
    - sourceline: 'ppa:openshot.developers/libopenshot-daily'
    - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
    packages: &p_common
    - gcc-4.8
    - cmake
    - pkg-config
    - swig
    - libopenshot-audio-dev
    - libfdk-aac-dev
    - libmagick++-dev
    - libunittest++-dev
    - libzmq3-dev
    - python3-dev
    - qtbase5-dev
    - qtmultimedia5-dev
    - libavcodec-dev
    - libavformat-dev
    - libavdevice-dev
    - libavutil-dev
    - libavfilter-dev
    - libswscale-dev
    - libpostproc-dev
    - libavresample-dev
    - libswresample-dev

matrix:
  include:
    - env: BUILD_VERSION=ffmpeg2
      addons:
        apt:
          sources: 
          - *s_common
          packages: 
          - *p_common

    - env: BUILD_VERSION=ffmpeg3
      addons:
        apt:
          sources:
          - *s_common
          - sourceline: 'ppa:jonathonf/ffmpeg-3'
          packages:
          - *p_common
          - libavcodec57
          - libavformat57
          - libavdevice57
          - libavutil55
          - libavfilter6
          - libswscale4
          - libpostproc54
          - libavresample3
          - libswresample2

    - name: "FFmpeg 4"
      os: linux
      language: cpp
      env: BUILD_VERSION=ffmpeg4
      addons:
        apt:
          sources:
          - *s_common
          - sourceline: 'ppa:jonathonf/ffmpeg-4'
          packages:
          - *p_common
          - libavcodec58
          - libavformat58
          - libavdevice58
          - libavutil56
          - libavfilter7
          - libswscale5
          - libpostproc55
          - libavresample4
          - libswresample3

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_INSTALL_PREFIX="${TRAVIS_OS_NAME}-${BUILD_VERSION}-x64" -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - make os_test
      - make install DESTDIR=dist/
