language: cpp

addons:
  apt:
    packages: &p_common
    - cmake
    - swig
    - libopenshot-audio-dev
    - libmagick++-dev
    - libunittest++-dev
    - libzmq3-dev
    - qtbase5-dev
    - qtmultimedia5-dev
    packages: &ff_common
    - *p_common
    - libfdk-aac-dev
    - libavcodec-dev
    - libavformat-dev
    - libavdevice-dev
    - libavutil-dev
    - libavfilter-dev
    - libswscale-dev
    - libpostproc-dev
    - libavresample-dev
    - libswresample-dev

matrix:
  include:
  - name: "FFmpeg 2 Linux"
    env: BUILD_VERSION=ffmpeg2
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:openshot.developers/libopenshot-daily'
        - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
        packages:
        - *ff_common

  - name: "FFmpeg 3 Linux"
    env: BUILD_VERSION=ffmpeg3
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:openshot.developers/libopenshot-daily'
        - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
        - sourceline: 'ppa:jonathonf/ffmpeg-3'
        packages:
        - *ff_common
        - libavcodec57
        - libavformat57
        - libavdevice57
        - libavutil55
        - libavfilter6
        - libswscale4
        - libpostproc54
        - libavresample3
        - libswresample2

  - name: "FFmpeg 4 Linux"
    env: BUILD_VERSION=ffmpeg4
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'ppa:openshot.developers/libopenshot-daily'
        - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
        - sourceline: 'ppa:jonathonf/ffmpeg-4'
        packages:
        - *ff_common
        - libavcodec58
        - libavformat58
        - libavdevice58
        - libavutil56
        - libavfilter7
        - libswscale5
        - libpostproc55
        - libavresample4
        - libswresample3

  - name: "FFmpeg 4 MacOS"
    env: BUILD_VERSION=ffmpeg4_MacOS LIBOPENSHOT_DEPS_DIR=$HOME/libopenshot-osx QT_DIR=/usr/local/opt/qt LIBOPENSHOT_AUDIO_DIR=$HOME/libopenshot-osx RESVGDIR=$HOME/libopenshot-osx
    os: osx
    before_install:
    - brew info
    - brew tap jmuncaster/homebrew-header-only # For cppzmq
    - pushd ${HOME}
    - |
      if [ ! -f "$LIBOPENSHOT_DEPS_DIR/lib/libopenshot-audio.dylib" ]; then
        brew install --display-times unittest-cpp;
        git clone https://github.com/OpenShot/libopenshot-audio;
        mkdir -p libopenshot-audio/build;
        pushd libopenshot-audio/build;
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="$LIBOPENSHOT_DEPS_DIR" ..;
        make;
        make install;
        popd;
      fi
    - if [ ! -f "$LIBOPENSHOT_DEPS_DIR/lib/libresvg.dylib" ]; then
        brew install --display-times qt rust;
        git clone https://github.com/RazrFalcon/resvg.git;
        pushd resvg/capi && cargo build --verbose --release --features "qt-backend" && popd;
        mkdir -p $LIBOPENSHOT_DEPS_DIR/lib $LIBOPENSHOT_DEPS_DIR/include/resvg;
        cp resvg/target/release/libresvg.* $LIBOPENSHOT_DEPS_DIR/lib/;
        cp resvg/capi/include/*.h $LIBOPENSHOT_DEPS_DIR/include/resvg/;
        popd;
      fi
    install:
    - brew install --display-times cppzmq
    - brew install --display-times swig
    - brew install --display-times unittest-cpp
    - brew install --display-times imagemagick 
    - brew install --display-times ffmpeg
    after_failure:
    - brew config
    cache:
      directories:
      - $LIBOPENSHOT_DEPS_DIR

script:
  - mkdir -p build; cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_PREFIX_PATH:PATH="$(brew --prefix qt)" ..
  - make VERBOSE=1
  - make os_test
  - make install DESTDIR="$BUILD_VERSION"

