language: cpp
os:
  - linux
  - osx
dist: xenial
sudo: required

addons:
  apt:
    packages: &p_common
    - cmake
    - swig
    - libopenshot-audio-dev
    - libmagick++-dev
    - libunittest++-dev
    - libzmq3-dev
    - qtbase5-dev
    - qtmultimedia5-dev
    packages: &ff_common
    - *p_common
    - libfdk-aac-dev
    - libavcodec-dev
    - libavformat-dev
    - libavdevice-dev
    - libavutil-dev
    - libavfilter-dev
    - libswscale-dev
    - libpostproc-dev
    - libavresample-dev
    - libswresample-dev

matrix:
  include:
    - name: "FFmpeg 2"
      env: BUILD_VERSION=ffmpeg2
      addons:
        apt:
          sources:
          - sourceline: 'ppa:openshot.developers/libopenshot-daily'
          - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
          packages:
          - *ff_common

    - name: "FFmpeg 3"
      env: BUILD_VERSION=ffmpeg3
      addons:
        apt:
          sources:
          - sourceline: 'ppa:openshot.developers/libopenshot-daily'
          - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
          - sourceline: 'ppa:jonathonf/ffmpeg-3'
          packages:
          - *ff_common
          - libavcodec57
          - libavformat57
          - libavdevice57
          - libavutil55
          - libavfilter6
          - libswscale4
          - libpostproc54
          - libavresample3
          - libswresample2

    - name: "FFmpeg 4"
      env: BUILD_VERSION=ffmpeg4
      addons:
        apt:
          sources:
          - sourceline: 'ppa:openshot.developers/libopenshot-daily'
          - sourceline: 'ppa:beineri/opt-qt-5.10.0-xenial'
          - sourceline: 'ppa:jonathonf/ffmpeg-4'
          packages:
          - *ff_common
          - libavcodec58
          - libavformat58
          - libavdevice58
          - libavutil56
          - libavfilter7
          - libswscale5
          - libpostproc55
          - libavresample4
          - libswresample3

script:
  - mkdir -p build; cd build;
  - cmake -DCMAKE_BUILD_TYPE:STRING="Debug" ../
  - make VERBOSE=1
  - make os_test
  - make install DESTDIR="$BUILD_VERSION"
