version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true

platform:
  - x64
  - x86

image:
  - Visual Studio 2017
  - macos

# Remove the impossible build
# (ends up being a redundant 64-bit run)
matrix:
  exclude:
    - platform: x86
      image: macos

cache: &common install-cache

for:
# Windows (both)
-
  matrix:
    except:
      - image: macos
  cache:
    - *common
    - C:\msys64\mingw64\var\cache\pacman
    - C:\msys64\mingw32\var\cache\pacman
  init:
  - cmd: IF %PLATFORM% == x64 (set PLAT_BITS=64) ELSE (set PLAT_BITS=32)
  - cmd: IF %PLATFORM% == x64 (set PLAT_ARCH=x86_64) ELSE (set PLAT_ARCH=i686)
  - cmd: set PATH=C:\msys64\mingw%PLAT_BITS%\bin;c:\msys64\mingw%PLAT_BITS%\lib;%PATH%
  - cmd: set LIBOPENSHOT_CACHE="%APPVEYOR_BUILD_FOLDER%\install-cache\%PLAT_ARCH%\bin\libopenshot-audio.dll"
  - cmd: set CMAKE_EXTRA_ARGS="-DENABLE_RUBY=0 -DOpenShotAudio_ROOT=..\install-cache\%PLAT_ARCH%"
  - cmd: c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-%PLAT_ARCH%-toolchain base-devel"

  install:
  - cmd: c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S
        mingw-w64-%PLAT_ARCH%-toolchain base-devel"
  - cmd: c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-cmake
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-doxygen
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-ffmpeg
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-zeromq
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-swig
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-python3-pyqt5
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-python3-pip"
  - cmd: pip3 install httplib2

  before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: IF NOT EXIST %LIBOPENSHOT_CACHE% appveyor\build-libopenshot-audio.bat
  - cmd: IF NOT EXIST install-cache\%PLAT_ARCH%\bin mkdir install-cache\%PLAT_ARCH%\bin
  - cmd: IF EXIST install-cache\%PLAT_ARCH%\lib\libopenshot-audio.dll move install-cache\%PLAT_ARCH%\lib\libopenshot-audio.dll install-cache\%PLAT_ARCH%\bin\

  build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake  -DCMAKE_INSTALL_PREFIX:PATH=install-%PLATFORM% -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_CXX_FLAGS_DEBUG="-Wall -Wpedantic" %CMAKE_EXTRA_ARGS% -G "MinGW Makefiles"  ..
  - cmd: cmake --build . -- VERBOSE=1
  #XXX: TESTS DISABLED, FAILING
  #- cmd: cmake --build . --target test
  - cmd: cmake --build . --target doc -- VERBOSE=1
  - cmd: cmake --build . --target install

# macOS
-
  matrix:
    only:
      - image: macos
  init:
  - sh: export PLAT_ARCH="macos-x64"
  - sh: export LIBOPENSHOT_CACHE="${APPVEYOR_BUILD_FOLDER}/install-cache/${PLAT_ARCH}/lib/libopenshot-audio.dylib"
  - sh: export CMAKE_EXTRA_ARGS="-DOpenShotAudio_ROOT=../install-cache/${PLAT_ARCH}"
  install:
  - sh: brew install
        gcc@9 libomp swig unittest-cpp rust qt
        imagemagick libvpx x264 x265
        fdk-aac fdk-aac-encoder ffmpeg zeromq
  before_build:
  - sh: mkdir build
  - sh: if [ \! -e "${LIBOPENSHOT_CACHE}" ]; then
          mkdir libopenshot-audio-build; pushd libopenshot-audio-build;
          cmake -DCMAKE_INSTALL_PREFIX=../install-cache/${PLAT_ARCH}/ ../libopenshot-audio;
          cmake --build . -- VERBOSE=1;
          cmake --build . --target install -- VERBOSE=1;
          popd;
        fi
  - sh: git clone https://github.com/zeromq/cppzmq;
        cd cppzmq;
        cmake $(brew diy --name cppzmq --version $(sh ./version.sh)) -DENABLE_DRAFTS=0 .;
        cmake --build . -- VERBOSE=1;
        cmake --build . --target install;
        cd ..
  - sh: eval $(brew --env|grep -i cmake);
        export CMAKE_EXTRA_ARGS="${CMAKE_EXTRA_ARGS} -DFFmpeg_ROOT=$(brew --prefix ffmpeg)"
  build_script:
  - sh: mkdir -p build; cd build;
  - sh: cmake -DCMAKE_INSTALL_PREFIX:PATH=install-${PLAT_ARCH} -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_CXX_FLAGS_DEBUG="-Wall -Wpedantic" ${CMAKE_EXTRA_ARGS} ../
  - sh: cmake --build . -- VERBOSE=1
  - sh: cmake --build . --target test
  - sh: cmake --build . --target install

test: off
