version: 1.0.{build}
image: Visual Studio 2015
environment:
  APPVEYOR_RDP_PASSWORD:
    secure: JoBWH3vCpaoh7UcfBjo57g==
cache: build\install-x64
nuget:
  account_feed: true
  project_feed: true

install:
- cmd: >-
    set PATH=C:\MSYS64\mingw64\bin;C:\msys64\mingw64\lib;%PATH%

    c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain base-devel"

    c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw64/mingw-w64-x86_64-ffmpeg mingw64/mingw-w64-x86_64-python3-pyqt5 mingw64/mingw-w64-x86_64-swig mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-doxygen mingw64/mingw-w64-x86_64-python3-pip mingw64/mingw-w64-x86_64-zeromq mingw64/mingw-w64-x86_64-python3-pyzmq mingw64/mingw-w64-x86_64-python3-cx_Freeze"

    c:\msys64\usr\bin\bash -lc "pip3 install httplib2"

    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    echo "DISABLED: git clone https://github.com/unittest-cpp/unittest-cpp"

    echo "DISABLED: mkdir unittest-cpp-build"

    echo "DISABLED: cd unittest-cpp-build"

    echo 'DISABLED: cmake -DCMAKE_INSTALL_PREFIX=..\build\install-x64 -G "MinGW Makefiles" ..\unittest-cpp'

    echo "DISABLED: cmake --build . -- VERBOSE=1"

    echo "DISABLED: mingw32-make install"

    echo "DISABLED: cd .."

    IF NOT EXIST build\install-x64 appveyor\build-libopenshot-audio.bat

# The build will pause here and wait for an RDP connection
before_build:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
- cmd: >-

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=install-x64 -DENABLE_TESTS=0 -DOpenShotAudio_ROOT=install-x64 -G "MinGW Makefiles" ..

    cmake --build . -- VERBOSE=1

    echo "TESTS DISABLED, UnitTest++ not working: mingw32-make test"

    mingw32-make install

    cd ..

test: off

artifacts:
- path: build/install-x64
  name: libopenshot-install
deploy:
- provider: NuGet
  api_key:
    secure: gbPd2Mk9DYcXyoURZhb2rWD7dK797HlDE34z5pv3YYNa2AqTilrFw/uoOzMhANQx
  username:
    secure: 1REhby0tYwDyTOSnedXePw==

