version: 1.0.{build}
image: Visual Studio 2015
environment:
  APPVEYOR_SSH_KEY:
    secure: qraMtHSme0UJRT+hr5MSxJZIuaJ9ytkwyjW4WG8edHlEkLF8OWFHAo9oA/cIrQcWoxhYAm6J1D5VC9khZRbScvaJ6gmO3a+jg+ms9oGqmXtf3TAalOzR3PEg2WQavxE8WCkpmGgdI+3AmDev6wK9TSLIuyM5jk05ckjiYVlhyH4jLQv2nR8rmv7c2KdcXrbxrZ71rYNaMKf/Os0h5Usu/HRwJuw2nXw5lSfzkWN/JkDl+PVnSvOoOcskDdES6fFlq7x1ENLcjdHq0r5ZRRdWuZSP0akqpcz8jTKnivZ4hRfndIe6Uq1034z1VY6EPhDNC2qCvs4l8PktYvtd15PFIXnNuRaRsXwBHbvYRFcC8+QPfmci2UYEzSsVCbpEpL/Xra6zm1qJfpUEu6g0sL6ys7gxG0f0nsms2Xz4OlZM8aoroMaDkHZA1Fywq9nDEE3wZ3yAiOEy6cKVaUSauyH/V5z4oWNZrDddcITlzFl5zJBQkoG7pwl4fozmXiT4dDCCY6Jpxy8KJl6SYWimN60yBvY9yvOYBIacg3DUW/RChRX6GD/HhZlrhyJd6FRfEhYWnL021VzW6fXCpzYP1d5N0EMfpwL+11UVcZB4sJe9UoNhFgiem8vQX+KHPAHvDQzqSXNCAc5iaL2/3kKphTwO0GyJCdN9gYlOMR62ZVVROthpSvoT1sLDMNOBGAeA6X9xKLV3vY6zgzTyjXx7SwwUDRReeD9dSw4iMf9Vk0VHmrFMaxU3miQ+AQO1TdFL8Vrq
  APPVEYOR_SSH_BLOCK: true
cache: build\install-x64
nuget:
  account_feed: true
  project_feed: true

init:
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

before_build:
- cmd: >-
    set PATH=C:\MSYS64\mingw64\bin;C:\msys64\mingw64\lib;%PATH%

    c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw-w64-x86_64-toolchain base-devel"

    c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S mingw64/mingw-w64-x86_64-ffmpeg mingw64/mingw-w64-x86_64-python3-pyqt5 mingw64/mingw-w64-x86_64-swig mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-doxygen mingw64/mingw-w64-x86_64-python3-pip mingw64/mingw-w64-x86_64-zeromq mingw64/mingw-w64-x86_64-python3-pyzmq mingw64/mingw-w64-x86_64-python3-cx_Freeze"

    c:\msys64\usr\bin\bash -lc "pip3 install httplib2"

    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    echo "DISABLED: git clone https://github.com/unittest-cpp/unittest-cpp"

    echo "DISABLED: mkdir unittest-cpp-build"

    echo "DISABLED: cd unittest-cpp-build"

    echo 'DISABLED: cmake -DCMAKE_INSTALL_PREFIX=..\build\install-x64 -G "MinGW Makefiles" ..\unittest-cpp'

    echo "DISABLED: cmake --build . -- VERBOSE=1"

    echo "DISABLED: mingw32-make install"

    echo "DISABLED: cd .."

    IF NOT EXIST build\install-x64 appveyor\build-libopenshot-audio.bat

build_script:
- cmd: >-

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=install-x64 -DENABLE_TESTS=0 -DOpenShotAudio_ROOT=install-x64 -G "MinGW Makefiles" ..

    cmake --build . -- VERBOSE=1

    echo "TESTS DISABLED, UnitTest++ not working: mingw32-make test"

    mingw32-make install

    cd ..

test: off

artifacts:
- path: build/install-x64
  name: libopenshot-install
deploy:
- provider: NuGet
  api_key:
    secure: gbPd2Mk9DYcXyoURZhb2rWD7dK797HlDE34z5pv3YYNa2AqTilrFw/uoOzMhANQx
  username:
    secure: 1REhby0tYwDyTOSnedXePw==

