version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true

platform:
  - x64
  - x86

image:
  - Visual Studio 2019
  - Visual Studio 2017

init:
  - cmd: IF %PLATFORM% == x64 (set PLAT_BITS=64) ELSE (set PLAT_BITS=32)
  - cmd: IF %PLATFORM% == x64 (set PLAT_ARCH=x86_64) ELSE (set PLAT_ARCH=i686)
  - cmd: set PATH=C:\msys64\mingw%PLAT_BITS%\bin;c:\msys64\mingw%PLAT_BITS%\lib;%PATH%
  - cmd: IF %PLATFORM% == x86 set CMAKE_EXTRA_ARGS="-DENABLE_RUBY=0"

install:
  - cmd: c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S
        mingw-w64-%PLAT_ARCH%-toolchain base-devel"
  - cmd: c:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -S
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-cmake
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-doxygen
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-qt5
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-qtwebkit
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-ffmpeg
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-zeromq
        mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-swig"

# Disabled packages (too many dependencies/too slow)
# mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-imagemagick
# mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-python3-pyqt5
# mingw%PLAT_BITS%/mingw-w64-%PLAT_ARCH%-python3-pip
# - cmd: pip3 install httplib2

before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: appveyor\build-libopenshot-audio.bat
  - cmd: IF NOT EXIST install-%PLAT_ARCH%\bin mkdir install-%PLAT_ARCH%\bin
  - cmd: IF EXIST install-%PLAT_ARCH%\lib\libopenshot-audio.dll copy install-%PLAT_ARCH%\lib\libopenshot-audio.dll install-%PLAT_ARCH%\bin\

build_script:
  - cmd: cmake -B build-%PLAT_ARCH% -S . -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%\install-%PLAT_ARCH% -DOpenShotAudio_ROOT=%APPVEYOR_BUILD_FOLDER%\install-%PLAT_ARCH% -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-Wall -Wpedantic" %CMAKE_EXTRA_ARGS% -G "MinGW Makefiles"
  - cmd: cmake --build build-%PLAT_ARCH% --verbose
  #XXX: TESTS DISABLED, FAILING
  #- cmd: cmake --build . --target test
  - cmd: cmake --build build-%PLAT_ARCH% --target doc --verbose
  - cmd: cmake --install build-%PLAT_ARCH% --verbose

test: off

artifacts:
- path: install-%PLAT_ARCH%
  name: libopenshot-%PLAT_ARCH%
